### ISSUE TITLE
Language Display Names data needs to be recreated

### ISSUE THREAD

**Issue by echeran** [unicode-org/conformance#201]
We need to recreate language display name data so that we can have a source of test input data which:

- is based on open source ICU
- provides the ICU version it is based on
- provides the values for the various options for display name formatting used

**Comment by saumyabharti294** [comment]
Hello @echeran 
I picked up the ICU For python testing and i want to know that json file for the same needs to be converted to python? If yes then are the steps below is what i need to follow?

1.Load JSON Data: Parse the JSON data for each test case.

2.Access Test Scenario: Retrieve the test scenario from the parsed data.

3.Access Verifications: Iterate through the verifications for the test case.

4.Perform Actions: Based on the test scenario and verifications, perform any necessary actions such as executing tests, verifying results, and generating reports.

5.Repeat for Each Test Case: Repeat the process for each test case in your dataset.

Also after this we have to run the code on some specific platform or we can run on local python environment?

**Comment by sven-oly** [comment]
Based on discussion today, here are notes on what we plan to do:

1. Update this to "locale display names" because the CLDR data includes more information than just language names, e.g., the names of digits in languages.
2. The newly generated CLDR localeDisplayName.txt data includes a subset of test locales for each locale, not all locales names in all locales. This substantially reduces the size of the testing needed while still covering interesting test cases.
3. The data now includes "regular" names for regions vs. "dialect" names. These should be added to the JSON data as a parameter and to each executor as a testing option.
4. The format of localeDisplayName.txt requires new code to parse for creating the JSON test cases.
5. Executors will need to be updated to handle the "dialect" option in test data.
6. The code for generating localeDisplayName.txt is being added to CLDR 76. To use locale display names for previous ICU/CLDR versions, we need to run this test code with previous CLDR versions, e.g., 45, 44, etc.

**Comment by sven-oly** [comment]
One more thing: to actually incorporate the localeDisplayName.txt data into DDT, we'll copy the file from the CLDR github repository into the testgen/icuXX directory. Perhaps this data could be automatically fetched from github rather than being manually added to the conformance repository.

**Comment by sffc** [comment]
All sounds good.
