### ISSUE TITLE
Add schema validation for date/time, list format, relative date/time format.

### ISSUE THREAD

**Issue by sven-oly** [unicode-org/conformance#213]

**Comment by echeran** [comment]
## Background & Summary

The root README visible from the [project homepage](https://github.com/unicode-org/conformance) explains the various stages of work involved in order to run these tests. We convert existing sources of test data into a JSON format when we're creating test cases. We also write the result of executing each test cases in a JSON format. We create schema files using JSON Schema to define what structure of JSON and/or what values in that structure are valid.

For every "component" of functionality in our internationalization (i18n) library that we test, we have a separate structure for input and output data, since the corresponding APIs for each functionality component are different from each other. Examples of functionality components are number formatting, likely subtags (locale identifier maximization / minimization), and language display names. These functionality components will be represented in [our test result dashboard](https://unicode-org.github.io/conformance/) as separate rows.

Code and test data have been added (or are in the process of being added) to the repository for the components like datetime formatting, list formatting, and relative datetime formatting. 

This task represents adding JSON schema files for one of these new components. These components code and test data are being added in #183 .

## Requirements

* a Debian/Ubuntu Linux system
* python3 installed
* the `jq` command line tool installed

## Details

* schema files exist in the `schema` directory, which is further subdivided into folders based on the identifier for the  component
* the full end-to-end script is at `generateDataAndRun.sh`. The schema additions must work and be executed by the end-to-end script, such that the script successfully runs without errors up through to and including the point where it runs `check_schemas.py` and `check_generated_data.py`

**Comment by sven-oly** [comment]
I think this is now implemented.

**Comment by sffc** [comment]
@echeran Is it fixed?

**Comment by sven-oly** [comment]
Resolving this one now!
